config/routes.rb
Rails.application.routes.draw do
  resources :books
  patch 'books/:id' => 'books#update', as: 'update_book'
  root to: 'homes#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book was successfully created."
     redirect_to book_path(@book.id)
    else
     @books = Book.all
     render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
        flash[:updated] = "Book was successfully updated."
         redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:alret] = "Book was successfully destroyed."
    redirect_to '/books'
  end

  private
  def book_params
   params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorが発生しました
   <ul>
    <% @book.errors.full_messages.each do |message| %>
     <li><%= message %></li>
      <% end %>
       </ul>
       <% end %>

<%= form_with model: @book, url: update_book_path(@book.id), method: :patch do |f| %>

<div class="field">
    <label for="title">Title</label>
     <div class="title_text">
      <%= f.text_field :title %>
     </div>
    </div>

<div class="field">
    <label for="body">Body</label>
     <div class="body_text">
      <%= f.text_area :body %>
     </div>
    </div>

<div class="actions">
 <%= f.submit 'Update Book' %>
</div>

<% end %>

<table>
  <td><%= link_to "Show", book_path(@book.id), :style=>"color:black;" %></td>
  <td>|</td>
  <td><%= link_to "Back", books_path, :style=>"color:black;" %></td>
</table>

app/views/books/index.html.erb
<html>
  <head>

  </head>

<body>
  <p class="text-success">
    <%= flash[:alret] %>
    </p>
<h1>Boooks</h1>
<table>
  <thead>
    <tr>
    <th>Title</th>
    <th>Body</th>
    <th colspan="3"></th>
    </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
      <tr>
      <td>
        <span><%= book.title %></span>
        </td>
      <td>
        <span><%= book.body %></span>
        </td>
        <td>
          <span><%= link_to "Show", book_path(book.id), :style=>"color:black;" %></span>
        </td>
        <td>
            <%= link_to "Edit", edit_book_path(book.id), :style=>"color:black;" %>
        </td>
        <td>
          <%= link_to "Destroy", book_path(book.id), method: :delete, data: {confirm: "本当に削除しますか？"}, :style=>"color:black;" %>
        </td>
        </tr>
      <% end %>
    </tbody>
    </table>

    <h2>New book</h2>

    <% if @book.errors.any? %>
     <%= @book.errors.count %>件のerrorが発生しました
     <ul>
       <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
        </ul>
        <% end %>

    <%= form_with model: @book, url: '/books', method: :post do |f| %>

    <div class="field">
      <label for="title">Title</label>
       <div class="title_text">
        <%= f.text_field :title %>
        </div>
      </div>

    <div class="field">
      <label for="body">Body</label>
       <div class="body_text">
        <%= f.text_area :body %>
        </div>
      </div>

    <div class="field">
    <%= f.submit 'Create Book' %>
    </div>
    <% end %>
</body>
</html>

app/views/books/new.html.erb
<h2>New book</h2>

<%= form_with model: @book, url: '/books', method: :post do |f| %>

<h4>Title</h4>
<%= f.text_field :title %>

<h4>Body</h4>
<%= f.text_area :body %>

<%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<body>
<p class="text-success">
  <%= flash[:notice] %>
  <%= flash[:updated] %>
</p>
<p>
  <strong>title: </strong>
   <%= @book.title %>
  </p>

<p>
  <strong>body: </strong>
   <%= @book.body %>
  </p>

<table>
   <td><%= link_to "Edit", edit_book_path(@book.id), :style=>"color:black;" %></td>
  <td>|</td>
   <td><%= link_to "Back", books_path, :style=>"color:black;" %></td>
</table>
</body>

app/views/homes/top.html.erb
<h1>
  ようこそ
<strong>Bookers</strong>
 へ！
</h1>
<p>
  <strong>Bookers</strong>
  では、さまざまな書籍に関するあなやの意見や
</p>
 <p>印象を共有し交換することができます</p>
<p>
  <%= link_to "start", "/books" %>
  </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebCampBackendNew</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>